name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build:prod

      - name: linting
        run: npm run lint:ts
        if: always()

      - name: linting css
        run: npm run lint:css
        if: always()
      - name: unit test
        run: npm run test:unit
        if: always()

#      - name: storybook build
#        run: npm run storybook:build
#
#      - name: screenshot test
#        run: npm run test:ui:ci
